import type { Lang } from '../lib/parsePost'

export type HomeCopy = typeof FI

const FI = {
  // NAV
  navManifesto: 'Manifesti', navProjects: 'Projektit', navTech: 'Tech',
  navStory: 'Tarina', navBlog: 'Blogi', navCta: 'Ota yhteyttä', navLangSwitch: 'In English',
  // HERO — NEW COPY (positioning change)
  heroBadge: 'Avoinna uusille projekteille',
  heroTitleA: 'Tuotteita, jotka pyörivät', heroTitleB: 'tuotannossa.', heroTitleC: 'Ei demoja.',
  heroSub: 'Sami Kiias · CTO @ Rascal AI · Founder @ Mak8r.fi',
  heroBody:
    'Rakennan fullstack-tuotteita ideasta tuotantoon: multi-tenant SaaS, mobiilisovellukset ja AI-integraatiot. Kuusi rakennettua tuotetta — kolme tuotannossa maksavilla asiakkailla. 11 vuotta yrittäjyyttä: puhun sekä bisneksen että koodin kieltä.',
  heroCta1: 'Keskustellaan projektista', heroCta2: 'Katso projektit',
  heroStat1v: '6', heroStat1l: 'Tuotetta rakennettu',
  heroStat2v: '400k+', heroStat2l: 'Riviä koodia tuotannossa',
  heroStat3v: '3 000+', heroStat3l: 'Automaattitestiä',
  heroTerminalTitle: 'koneisto — tuotanto',
  // KONEISTO (live section) — NEW COPY: the site's own real lead pipeline
  koneistoLive: 'Live · tämän sivun oma putki',
  koneistoTitleA: 'Näin yhteydenottosi', koneistoTitleB: 'kulkee tällä sivulla',
  koneistoLead:
    'Ei kuvitteellista demoa: tämä on tämän sivuston oma liidiputki. Jokainen lomakkeen lähetys kulkee tämän läpi — validoinnista tallennukseen ja notifikaatioon.',
  kStep1t: 'Lomake täytetty', kStep1s: 'React · honeypot-suojaus',
  kStep2t: 'Validointi', kStep2s: 'Vercel Function',
  kStep3t: 'Tallennus', kStep3s: 'Neon Postgres',
  kStep4t: 'Markkinointilupa?', kStep4s: 'suostumus talteen',
  kStep5t: 'Brevo-lista', kStep5s: 'jos lupa annettu',
  kStep6t: 'Notifikaatio', kStep6s: '✓ sähköposti minulle',
  koneistoLogTitle: 'Execution log · /api/contact',
  koneistoFootnote: 'Sama arkkitehtuuri, jolla rakennan asiakkaille — pienoiskoossa.',
  // MANIFESTI — rewritten with per-principle titles + receipts (2026-07-29)
  manEyebrow: '— Periaatteet', manTitleA: 'Automaatio on', manTitleB: 'uusi lukutaito.',
  manIntro: 'Ei teesejä joita kukaan ei voi vastustaa — vaan säännöt, joiden mukaan nämä kuusi tuotetta on oikeasti rakennettu. Jokaisessa on kuitti.',
  man1t: 'Tuotanto on ainoa mittari.',
  man1: 'Demo ei todista mitään. Järjestelmä on valmis vasta, kun se pyörii maksavilla asiakkailla myös silloin kun kukaan ei katso.',
  man1r: 'kuitti: 423 julkaisua tuotantoon ~13 kk:ssa',
  man2t: 'Tylsä matikka ensin, AI vasta sitten.',
  man2: 'Kaiken minkä voi laskea deterministisesti, lasken koodilla — auditoitavasti ja ilmaiseksi. LLM saa harkinnan, ei kirjanpitoa.',
  man2r: 'kuitti: Altion progressiomoottori · Pesän senttitarkka vyörytys',
  man3t: 'Turva ei ole ominaisuus.',
  man3: 'Eristys tehdään tietokannassa asti, ei käyttöliittymässä. Virhetilanne sulkee oven — ei koskaan avaa väärän asiakkaan dataa.',
  man3r: 'kuitti: RLS 78+50 taulussa · fail-closed-korjaus tuotannossa',
  man4t: 'Kolmas toisto automatisoidaan.',
  man4: 'Kahdesti käsin, kolmannella kerralla koneelle. Pienistä toistoista kertyy viikkoja — ja koneisto ei unohda.',
  man4r: 'kuitti: 27 edge-funktiota hoitaa julkaisut, token-refreshit ja healthcheckit',
  man5t: 'Rakennan kun se on etu, ostan kun ei ole.',
  man5: 'Oma workflow-moottori siellä missä se erottaa tuotteen — valmis Twilio siellä missä ei. Raja on kilpailuetu, ei ideologia.',
  man5r: 'kuitti: oma OAuth 2.1 -palvelin · ostettu puheluinfra',
  man6t: 'Nopeus tulee kurista.',
  man6: 'Speksi ennen koodia, testit ennen mergeä, julkaisu joka päivä. Kuri ei hidasta — se poistaa pelon muuttaa mitä vain.',
  man6r: 'kuitti: ~3 000 testiä · 65+ design-spekkiä',
  // TECH — keep existing FI verbatim (eyebrow, title, intro, 5 layers × (name+desc), 3 principles × (title+body))
  techEyebrow: '02 — Rakennettu, ei ostettu', techTitle: 'Näin rakennan koneiston',
  techIntro: 'En osta valmista markkinointi- tai tuotekoneistoa. Rakennan sen — AI-natiivina päättelystä ajoon, kytkettynä yhteen APIn yli. Sama stack pyörittää sekä omia tuotteitani että asiakasprojekteja.',
  techL1n: 'Reasoning', techL1d: 'Päättely ja generointi. Claude vetää tuotannossa ja kehityksessä — muut mallit erikoistehtäviin ja vertailuun.',
  techL2n: 'Build', techL2d: 'Agenttinen kehitys. Kirjoitan järjestelmät Claude Codella ja kytken työkalut MCP:llä — APIn yli, ei käyttöliittymää klikkaamalla.',
  techL3n: 'Product', techL3d: 'Missä järjestelmät ajetaan. Multi-tenant SaaS, RLS-eristetty data, vektorihaut ja edge-deploy jokaiselle muutokselle.',
  techL4n: 'Automation', techL4d: 'Koneiston liima. Self-hosted n8n hoitaa workflowt, webhookit ja integraatiot palasta toiseen — täysi kontrolli dataan.',
  techL5n: 'Generative media', techL5d: 'AI-natiivi sisältö. Kuva, video, ääni ja avatarit promptista valmiiksi materiaaliksi — sama API-logiikka kuin muuallakin.',
  techP1t: '01 · API-first', techP1b: 'Lähes kaikki ajetaan rajapintojen yli, ei käyttöliittymistä klikkaamalla. Koneisto, ei kasa tilauksia.',
  techP2t: '02 · Rakennettu, ei ostettu', techP2b: 'Kun rakentaminen kannattaa, rakennan sen itse. Ostan vain siellä missä se ei oikeasti kannata.',
  techP3t: '03 · Sama stack, oikeat asiakkaat', techP3b: 'Tämä ei ole demo-stack. Sama koneisto pyörittää Rascal AI:ta ja asiakasprojekteja tuotannossa.',
  // BUILD IN PUBLIC static intro
  bipEyebrow: '03 — YouTube · @samikiias', bipTitle: 'Build in Public',
  bipIntro: 'Dokumentoin matkaa AI-järjestelmien rakentajana. Tutoriaaleja, projektien läpikäyntejä ja rehellisiä ajatuksia.',
  // TARINA — keep existing FI verbatim; NOTE: update the 2025 entry to 2025–2026 & product-builder angle
  storyEyebrow: '04 — Tarina', storyTitle: 'Yrittäjästä AI-rakentajaksi',
  storyIntro: 'Epätyypillinen polku yrittäjästä AI-järjestelmien rakentajaksi. Jokainen vaihe toi uuden näkökulman.',
  story1y: '2015', story1r: 'Yrittäjä', story1o: 'Ensimmäinen yritys',
  story1b: 'Aloitin yrittäjänä. Opin ymmärtämään asiakkaita, myyntiä ja liiketoiminnan perusteita käytännön kautta.',
  story2y: '2022', story2r: 'Markkinoija', story2o: 'Haaga-Helia',
  story2b: 'Liiketalouden tradenomi markkinoinnin suuntautumisella. Digitaalinen markkinointi ja analytiikka.',
  story3y: '2024', story3r: 'Kehittäjä', story3o: 'Full-stack',
  story3b: 'Itseoppinut kehittäjä. React, TypeScript, Node.js ja modernit pilvipalvelut. Ideat muuttuivat tuotteiksi.',
  story4y: '2025', story4r: 'CTO & tuoterakentaja', story4o: 'Rascal AI',
  story4b: 'Rakennan tuotteita, jotka pyörivät tuotannossa maksavilla asiakkailla: kolme Rascal-tuotetta ja kolme omaa sovellusta — yli 400 000 riviä koodia.',
  storyQuote: '“Epätyypillinen tausta on vahvuus — ymmärrän sekä bisneksen että teknologian kielen.”',
  storyName: 'Sami Kiias', storyRole: 'CTO @ Rascal AI',
  storyStat1v: '11', storyStat1l: 'Vuotta yrittäjänä',
  storyStat2v: '6', storyStat2l: 'Tuotetta rakennettu',
  storyStat3v: '423', storyStat3l: 'Julkaisua tuotantoon',
  // YHTEYS — NEW angle
  contactEyebrow: '05 — Ota yhteyttä', contactTitleA: 'Rakennetaanko', contactTitleB: 'seuraava tuotteesi?',
  contactBody: 'Olipa kyse uudesta tuotteesta, MVP:stä tai AI-ominaisuudesta olemassa olevaan järjestelmään — kerro tilanteestasi, niin katsotaan miten se kannattaa rakentaa.',
  contactReply: 'Vastaan yleensä saman päivän aikana.',
  contactFollow: 'Seuraa ja verkostoidu',
  contactLi: 'LinkedIn', contactLiCta: 'Verkostoidu →',
  contactYt: 'YouTube', contactYtCta: 'Katso sisältöä →',
  contactGh: 'GitHub', contactGhCta: 'Tutustu koodiin →',
  contactCompanies: 'Yritykset',
  contactC1n: 'Rascal AI', contactC1d: 'AI-markkinointi ja -myynti pk-yrityksille — kolme tuotetta', contactC1r: 'CTO',
  contactC2n: 'Altio', contactC2d: 'AI-valmennussovellus — treeni, ravinto ja palautuminen', contactC2r: 'Solo Dev',
  contactC3n: 'Mak8r.fi', contactC3d: 'Tuotekehitys- ja AI-projektit toimeksiannosta', contactC3r: 'Founder',
}

const EN: HomeCopy = {
  navManifesto: 'Manifesto', navProjects: 'Projects', navTech: 'Tech',
  navStory: 'Story', navBlog: 'Blog', navCta: 'Get in touch', navLangSwitch: 'Suomeksi',
  heroBadge: 'Open for new projects',
  heroTitleA: 'Products that run', heroTitleB: 'in production.', heroTitleC: 'Not demos.',
  heroSub: 'Sami Kiias · CTO @ Rascal AI · Founder @ Mak8r.fi',
  heroBody:
    'I build fullstack products from idea to production: multi-tenant SaaS, mobile apps and AI integrations. Six products built — three in production with paying customers. 11 years of entrepreneurship: I speak both business and code.',
  heroCta1: 'Let’s talk about your project', heroCta2: 'See the projects',
  heroStat1v: '6', heroStat1l: 'Products built',
  heroStat2v: '400k+', heroStat2l: 'Lines of code in production',
  heroStat3v: '3,000+', heroStat3l: 'Automated tests',
  heroTerminalTitle: 'koneisto — production',
  koneistoLive: 'Live · this site’s own pipeline',
  koneistoTitleA: 'How your message', koneistoTitleB: 'travels on this site',
  koneistoLead:
    'Not a mock demo: this is this website’s own lead pipeline. Every form submission passes through it — validation, storage, notification.',
  kStep1t: 'Form submitted', kStep1s: 'React · honeypot guard',
  kStep2t: 'Validation', kStep2s: 'Vercel Function',
  kStep3t: 'Storage', kStep3s: 'Neon Postgres',
  kStep4t: 'Marketing consent?', kStep4s: 'consent recorded',
  kStep5t: 'Brevo list', kStep5s: 'if consent given',
  kStep6t: 'Notification', kStep6s: '✓ email to me',
  koneistoLogTitle: 'Execution log · /api/contact',
  koneistoFootnote: 'The same architecture I build for clients — in miniature.',
  manEyebrow: '— Principles', manTitleA: 'Automation is', manTitleB: 'the new literacy.',
  manIntro: 'Not theses nobody could disagree with — the actual rules these six products were built by. Each one comes with a receipt.',
  man1t: 'Production is the only scoreboard.',
  man1: 'A demo proves nothing. A system is done when it runs for paying customers even when nobody is watching.',
  man1r: 'receipt: 423 production releases in ~13 months',
  man2t: 'Boring math first, AI second.',
  man2: 'Everything that can be computed deterministically, I compute in code — auditable and free. The LLM gets judgment, never the bookkeeping.',
  man2r: 'receipt: Altio’s progression engine · Pesä’s cent-exact avalanche',
  man3t: 'Security is not a feature.',
  man3: 'Isolation goes down to the database, not the UI. Failure closes the door — it never opens another customer’s data.',
  man3r: 'receipt: RLS across 78+50 tables · a fail-closed fix in production',
  man4t: 'The third repetition gets automated.',
  man4: 'Twice by hand, third time to the machine. Small repetitions add up to weeks — and the machine doesn’t forget.',
  man4r: 'receipt: 27 edge functions run publishing, token refresh and health checks',
  man5t: 'Build where it’s an edge, buy where it isn’t.',
  man5: 'A custom workflow engine where it differentiates the product — off-the-shelf Twilio where it doesn’t. The line is competitive advantage, not ideology.',
  man5r: 'receipt: a from-scratch OAuth 2.1 server · bought call infrastructure',
  man6t: 'Speed comes from discipline.',
  man6: 'Spec before code, tests before merge, releases every day. Discipline doesn’t slow you down — it removes the fear of changing anything.',
  man6r: 'receipt: ~3,000 tests · 65+ design specs',
  techEyebrow: '02 — Built, not bought', techTitle: 'How I build the machine',
  techIntro: 'I don’t buy a ready-made marketing or product machine. I build it — AI-native from reasoning to runtime, wired together over APIs. The same stack runs my own products and client projects.',
  techL1n: 'Reasoning', techL1d: 'Inference and generation. Claude leads in production and development — other models for special tasks and comparison.',
  techL2n: 'Build', techL2d: 'Agentic development. I write systems with Claude Code and wire tools over MCP — through APIs, not by clicking UIs.',
  techL3n: 'Product', techL3d: 'Where systems run. Multi-tenant SaaS, RLS-isolated data, vector search and edge deploys for every change.',
  techL4n: 'Automation', techL4d: 'The machine’s glue. Self-hosted n8n runs workflows, webhooks and integrations end to end — full control of the data.',
  techL5n: 'Generative media', techL5d: 'AI-native content. Image, video, voice and avatars from prompt to finished material — the same API logic as everywhere else.',
  techP1t: '01 · API-first', techP1b: 'Almost everything runs over APIs, not by clicking UIs. A machine, not a pile of subscriptions.',
  techP2t: '02 · Built, not bought', techP2b: 'When building pays off, I build it myself. I buy only where building truly doesn’t.',
  techP3t: '03 · Same stack, real customers', techP3b: 'This is not a demo stack. The same machine runs Rascal AI and client projects in production.',
  bipEyebrow: '03 — YouTube · @samikiias', bipTitle: 'Build in Public',
  bipIntro: 'I document the journey of building AI systems. Tutorials, project walkthroughs and honest thoughts.',
  storyEyebrow: '04 — Story', storyTitle: 'From entrepreneur to AI builder',
  storyIntro: 'An unusual path from entrepreneur to builder of AI systems. Every stage added a new perspective.',
  story1y: '2015', story1r: 'Entrepreneur', story1o: 'First company',
  story1b: 'I started as an entrepreneur — learning customers, sales and business fundamentals hands-on.',
  story2y: '2022', story2r: 'Marketer', story2o: 'Haaga-Helia',
  story2b: 'BBA in business, specializing in marketing. Digital marketing and analytics.',
  story3y: '2024', story3r: 'Developer', story3o: 'Full-stack',
  story3b: 'Self-taught developer. React, TypeScript, Node.js and modern cloud. Ideas turned into products.',
  story4y: '2025', story4r: 'CTO & product builder', story4o: 'Rascal AI',
  story4b: 'I build products that run in production with paying customers: three Rascal products and three apps of my own — over 400,000 lines of code.',
  storyQuote: '“An unusual background is a strength — I speak both business and technology.”',
  storyName: 'Sami Kiias', storyRole: 'CTO @ Rascal AI',
  storyStat1v: '11', storyStat1l: 'Years as an entrepreneur',
  storyStat2v: '6', storyStat2l: 'Products built',
  storyStat3v: '423', storyStat3l: 'Releases shipped',
  contactEyebrow: '05 — Get in touch', contactTitleA: 'Shall we build', contactTitleB: 'your next product?',
  contactBody: 'A new product, an MVP, or an AI feature for an existing system — tell me where you are, and we’ll figure out how it should be built.',
  contactReply: 'I usually reply the same day.',
  contactFollow: 'Follow and connect',
  contactLi: 'LinkedIn', contactLiCta: 'Connect →',
  contactYt: 'YouTube', contactYtCta: 'Watch →',
  contactGh: 'GitHub', contactGhCta: 'See the code →',
  contactCompanies: 'Companies',
  contactC1n: 'Rascal AI', contactC1d: 'AI marketing & sales for SMBs — three products', contactC1r: 'CTO',
  contactC2n: 'Altio', contactC2d: 'AI coaching app — training, nutrition and recovery', contactC2r: 'Solo Dev',
  contactC3n: 'Mak8r.fi', contactC3d: 'Product development and AI projects on commission', contactC3r: 'Founder',
}

export const homeCopy: Record<Lang, HomeCopy> = { fi: FI, en: EN }
